CREATE DATABASE coffeshop;
USE coffeshop;

Create Login mylogin with password='mylogin', 
CHECK_POLICY = OFF 
sp_changedbowner mylogin

CREATE TABLE TableDrinks(
	TD_ID INT IDENTITY PRIMARY KEY,
	TD_NAME NVARCHAR(100),
	TD_STATUS NVARCHAR(100)
);
CREATE TABLE Accounts(
	ACC_USERNAME NVARCHAR(100) NOT NULL PRIMARY KEY,
	ACC_PWD NVARCHAR(100) NOT NULL DEFAULT 0,
	ACC_TYPE INT NOT NULL DEFAULT 0 
);
CREATE TABLE Menu(
	DRINK_NAME NVARCHAR(100),
	COUNT INT,
	PRICE FLOAT NOT NULL DEFAULT 0,
	TOTAL_PRICE FLOAT NOT NULL DEFAULT 0
);
CREATE TABLE Drinks(
	ID INT IDENTITY PRIMARY KEY,
	DR_NAME NVARCHAR(100) NOT NULL DEFAULT N'Chưa đặt tên',
	DR_PRICE FLOAT NOT NULL DEFAULT 0,
);
CREATE TABLE Bill(
	ID INT IDENTITY PRIMARY KEY,
	DATE_CHECKIN DATE NOT NULL DEFAULT GETDATE(),
	DATE_CHECKOUT DATE,
	ID_TABLE INT NOT NULL,
	BILL_STATUS INT NOT NULL DEFAULT 0,
	FOREIGN KEY (ID_TABLE) REFERENCES TableDrinks(TD_ID)
);
CREATE TABLE Bill_Infor(
	ID INT IDENTITY PRIMARY KEY,
	ID_BILL INT NOT NULL,
	ID_DRINKS INT NOT NULL,
	COUNT INT NOT NULL DEFAULT 0
	FOREIGN KEY (ID_BILL) REFERENCES Bill(ID),
	FOREIGN KEY (ID_DRINKS) REFERENCES Drinks(ID)
);
INSERT INTO Accounts (ACC_USERNAME, ACC_PWD, ACC_TYPE) VALUES (N'ADMIN', N'123ABC', 1);
INSERT INTO Accounts (ACC_USERNAME, ACC_PWD, ACC_TYPE) VALUES (N'STAFF01', N'123ABCDEF', 0);
SELECT * FROM Accounts;

INSERT INTO TableDrinks (TD_NAME, TD_STATUS) VALUES (N'B1', N'Trống');
INSERT INTO TableDrinks (TD_NAME, TD_STATUS) VALUES (N'B2', N'Trống');
INSERT INTO TableDrinks (TD_NAME, TD_STATUS) VALUES (N'B3', N'Trống');
INSERT INTO TableDrinks (TD_NAME, TD_STATUS) VALUES (N'B4', N'Trống');
INSERT INTO TableDrinks (TD_NAME, TD_STATUS) VALUES (N'B5', N'Trống');
SELECT * FROM TableDrinks;


INSERT INTO Drinks (DR_NAME, DR_PRICE) VALUES (N'Coffe đá/nóng', 20000);
INSERT INTO Drinks (DR_NAME, DR_PRICE) VALUES (N'Coffe sữa đá/nóng', 20000);
SELECT * FROM Drinks;

select * from Bill_Infor;
SELECT dr.dr_name, bi.count, dr.DR_PRICE, dr.DR_PRICE*bi.count AS totalPrice FROM Bill_Infor AS bi, Bill AS b, Drinks AS dr WHERE bi.id_bill = b.id AND bi.id_drinks = dr.id AND b.bill_status = 0 AND b.id_table = 1;